export const carData = [
  {
    id: 1,
    name: "Toyota Glanza",
    modal: "2023",
    type: "Manual",
    fuelType: "Petrol",
    mileage: "31km/L",
    engine: "1197 cc",
    price: "₹2-2.5K/day",
    imageUrls: [
      "/photos/toyotaGlanza/2.jpg",
      "/photos/toyotaGlanza/1.webp",
      "/photos/toyotaGlanza/glanzaMain.jpeg",
    ],

    about:
      "The Toyota Glanza has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1197 cc while the CNG engine is 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Glanza has a mileage of 22.35 kmpl to 30.61 km/kg . The Glanza is a 5 seater 4 cylinder car and has length of 3990, width of 1745 and a wheelbase of 2520.",
  },
  {
    id: 2,
    name: "Hyundai Creta",
    modal: "2020",
    type: "Manual",
    fuelType: "Desiel",
    mileage: "18 to 21km/L",
    engine: "1497 cc",
    price: "₹2-3K/day",
    imageUrls: [
      "https://imgd.aeplcdn.com/1200x900/n/cw/ec/46757/hyundai-creta-exterior22.jpeg?wm=0",
      "/photos/hyundaiCreta2/2.jpg",
      "/photos/hyundaiCreta2/1.jpeg",
      "/photos/hyundaiCreta/cretaMain.jpeg",
    ],
    about:
      "The Hyundai Creta has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1497 cc and 1482 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Creta has a mileage of 17.4 to 21.8 kmpl . The Creta is a 5 seater 4 cylinder car and has length of 4330, width of 1790 and a wheelbase of 2610.",
  },
  {
    id: 3,
    name: "Hyundai creata",
    modal: "2021",
    type: "Manual",
    fuelType: "Desiel",
    mileage: "18 to 21km/L",
    engine: "1497 cc",
    price: "₹2-3K/day",
    imageUrls: [
      "https://www.rushlane.com/wp-content/uploads/2021/08/hyundai-creta-price-increase-aug-2021-1200x900.jpg",
      "/photos/hyundaiCreta/1.jpg",
      "/photos/hyundaiCreta/2.jpg",
    ],
    about:
      "The Hyundai Creta has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1497 cc and 1482 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Creta has a mileage of 17.4 to 21.8 kmpl . The Creta is a 5 seater 4 cylinder car and has length of 4330, width of 1790 and a wheelbase of 2610.",
  },
  {
    id: 4,
    name: "Mahindra Thar hardtop",
    modal: "2022",
    price: "₹4-5K/day",
    mileage: "15.2km/L",
    engine: "1497 to 2184 cc",
    type: "Automatic",
    fuelType: "Desiel",
    imageUrls: [
      "/photos/mahindraThar2/1.jpg",
      "/photos/mahindraThar2/2.webp",
      "/photos/mahindraThar2/thar2Main.jpeg",
    ],
    about:
      "Mahindra Thar LX Hard Top Diesel AT 4WD is the top model in the Mahindra Thar lineup and the price of Thar top model is Rs. 17.20 Lakh. Mahindra Thar LX Hard Top Diesel AT 4WD is available in Automatic (TC) transmission and offered in 5 colours: Napoli Black, Aqua Marine, Galaxy Grey, Red Rage and Everest White.",
  },
  {
    id: 5,
    name: "Mahindra Thar hardtop gray 4x4",
    modal: "2023",
    price: "₹4-5K/day",
    mileage: "15.2km/L",
    engine: "1497 to 2184 cc",
    type: "Manual",
    fuelType: "Desiel",
    imageUrls: [
      "https://spn-mda.spinny.com/img/hK9_mA4NRZCINH7ny98tsw/tab/file.JPG",
      "/photos/mahindraThar/tharMain.jpeg",
      "/photos/mahindraThar/1.webp",
      "/photos/mahindraThar/2.jpeg",
    ],
    about:
      "Mahindra Thar LX Hard Top Diesel AT 4WD is the top model in the Mahindra Thar lineup and the price of Thar top model is Rs. 17.20 Lakh. Mahindra Thar LX Hard Top Diesel AT 4WD is available in Automatic (TC) transmission and offered in 5 colours: Napoli Black, Aqua Marine, Galaxy Grey, Red Rage and Everest White.",
  },
  {
    id: 6,
    name: "Hyundai verna",
    modal: "2022",
    price: "₹3-3.5K/day",
    mileage: "20km/L",
    engine: "1482 to 1497 cc",
    type: "Manual",
    fuelType: "Petrol",
    imageUrls: [
      "https://static.locowiz.com/locomedia/mahindra-first-choice/products/original/cover_image-20220828121955.jpeg",
      "/photos/hyundaiVerna/vernaMain.jpeg",
      "/photos/hyundaiVerna/2.jpeg",
      "/photos/hyundaiVerna/1.jpeg",
    ],
    about:
      "The Hyundai Verna is a 5-seater, 4-cylinder car with a 1.5-liter turbo GDi petrol engine. It has a length of 4,535 mm, a width of 1,765 mm, and a wheelbase of 2,670 mm. The Verna is available in 14 variants, with engine options ranging from 1482 to 1497 cc and a choice of 2 transmissions: Manual and Automatic",
  },
  {
    id: 7,
    name: "Maruti Fronx",
    modal: "2023",
    price: "₹2.5-3K/day",
    mileage: "29km/L",
    engine: "998 to 1197 cc",
    type: "Automatic",
    fuelType: "Petrol",
    imageUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/e/e8/2023_Suzuki_Fronx_1.2_Delta%2B_%28India%29_front_view.png",
      "/photos/marutifronx/fronxMain.jpeg",
      "/photos/marutifronx/1.webp",
      "/photos/marutifronx/2.jpg",
    ],
    about:
      "The Maruti FRONX has 2 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1197 cc and 998 cc while the CNG engine is 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the FRONX has a mileage of 20.01 kmpl to 28.51 km/kg . The FRONX is a 5 seater 3 cylinder car and has length of 3995mm, width of 1765mm and a wheelbase of 2520mm.",
  },
  {
    id: 8,
    name: "Suzuki Dzire VDI",
    modal: "2019",
    type: "Manual",
    mileage: "31km/L",
    engine: "1197 cc",
    fuelType: "Desiel",
    price: "₹2-2.5K/day",
    imageUrls: [
      "https://www.cartoq.com/wp-content/uploads/2022/02/dzire-used-featured.jpg",
      "/photos/marutiDezire/1.jpg",
      "/photos/marutiDezire/2.jpg",
    ],
    about:
      "When it comes to the Swift Dzires specifications, you will find that it is a 5-seater compact sedan measuring 3,995mm in length, 1735mm in width, 1515mm height and a 2450mm wheelbase.",
  },
  {
    id: 9,
    name: "Hyundai venue",
    modal: "2023",
    type: "Manual",
    mileage: "23km/L",
    engine: "998 to 1493 cc",
    fuelType: "Petrol",
    price: "₹2-2.5K/day",
    imageUrls: [
      "/photos/hyundaiVenue/1.jpg",
      "/photos/hyundaiVenue/2.jpg",
      "https://www.cartoq.com/wp-content/uploads/2023/09/hyundai-venue-black-knight-edition-1.jpg",
      '/photos/hyundaiVenue/venueMain.jpeg',
    ],
    about:
      "The Diesel engine is 1493 cc while the Petrol engine is 1197 cc and 998 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Venue has a mileage of 24.2 kmpl . The Venue is a 5 seater 3 cylinder car and has length of 3995mm, width of 1770mm and a wheelbase of 2500mm.",
  },
  {
    id: 10,
    name: "Mahindra Scorpio s11",
    modal: "2023",
    type: "Manual",
    mileage: "15km/L",
    engine: "2184 cc",
    fuelType: "Diesel",
    price: "₹4-5K/day",
    imageUrls: [
      "/photos/mahindraScor/scorpioMain.jpeg",
      "https://i.ytimg.com/vi/aaTFTWF4xPE/maxresdefault.jpg",
      "/photos/mahindraScor/1.jpeg",
    ],
    about:
      "The Mahindra Scorpio S11 is a 7-seater diesel car. It has a 2.2 L mHawk engine that produces 130 bhp @ 3750 rpm and 300 Nm @ 1500 rpm of torque. The S11 has a 6-speed manual transmission and a rear-wheel drive configuration",
  },
  {
    id: 11,
    name: "Maruti boleno ",
    modal: "2023",
    price: "₹2-2.5K/day",
    type: "Manual",
    mileage: "31km/L",
    engine: "1197 cc",
    fuelType: "Petrol",
    imageUrls: [
      "https://imgd.aeplcdn.com/1056x594/cw/ec/20478/Maruti-Suzuki-Baleno-Driving-58937.jpg?v=201711021421&wm=1&q=80",
      "/photos/marutiBlano/1.jpg",
      "/photos/marutiBlano/2.webp",
    ],
    about:
      "The Maruti Baleno has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1197 cc while the CNG engine is 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Baleno has a mileage of 22.35 kmpl to 30.61 km/kg . The Baleno is a 5 seater 4 cylinder car.",
  },
  {
    id: 12,
    name: "Creta",
    modal: "2019",
    price: "₹2.5-3K/day",
    type: "Manual",
    mileage: "22.1km/L",
    engine: "1396 to 1591 cc",
    fuelType: "Desiel",
    imageUrls: [
      "https://c.ndtvimg.com/hyundai-creta-facelift-review_625x300_1527234234351.jpg",
      "/photos/hyundaiCreta2/1.jpeg",
      "/photos/hyundaiCreta2/2.jpg",
    ],
    about:
      "The Hyundai Creta has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1497 cc and 1482 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Creta has a mileage of 17.4 to 21.8 kmpl . The Creta is a 5 seater 4 cylinder car and has length of 4330, width of 1790 and a wheelbase of 2610.",
  },
  {
    id: 13,
    name: "Honda Amaze",
    modal: "2020",
    price: "₹2-2.5K/day",
    type: "Manual",
    mileage: "23.8km/L",
    engine: "1498 cc",
    fuelType: "diesel",
    imageUrls: [
      "/photos/hondaAmaze/1.jpg",
      "/photos/hondaAmaze/2.avif",
      "/photos/hondaAmaze/amazeMain.jpeg",
      "https://static.locowiz.com/locomedia/mahindra-first-choice/products/original/cover_image-20230105150435.jpeg",
    ],
    about:
      "The Honda Amaze has 1 Petrol Engine on offer. The Petrol engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Amaze has a mileage of 18.3 to 18.6 kmpl . The Amaze is a 5 seater 4 cylinder car and has length of 3995mm, width of 1695 and a wheelbase of 2470.",
  },
  {
    id: 14,
    name: "Fortuner",
    modal: "2014",
    price: "₹4-5K/day",
    type: "Automatic",
    mileage: "12.5km/L",
    engine: "2982 cc",
    fuelType: "Diesel",
    imageUrls: [
      "https://fastly-production.24c.in/hello-ar/dev/uploads/981bb595-9072-4848-ad29-e238b41f5eae/9e507f6b-5cef-44e8-90de-e6c877e360be/43.jpg?w=750&auto=format",
      "/photos/toyotaFortuner/1.png",
      "/photos/toyotaFortuner/fortunerMain.jpeg",
    ],
    about:
      "The Diesel engine is 2755 cc while the Petrol engine is 2694 cc . It is available with Manual & Automatic transmission. Depending upon the variant and fuel type the Fortuner has a mileage of 10 kmpl . The Fortuner is a 7 seater 4 cylinder car and has length of 4795mm, width of 1855mm and a wheelbase of 2745mm.",
  },
  {
    id: 16,
    name: "Fortuner",
    modal: "2015",
    price: "₹4-5K/day",
    type: "Automatic",
    mileage: "12.5km/L",
    engine: "2982 cc",
    fuelType: "Diesel",
    imageUrls: [
      "/photos/toyotaFortuner/1.png",
      "https://fastly-production.24c.in/hello-ar/dev/uploads/981bb595-9072-4848-ad29-e238b41f5eae/9e507f6b-5cef-44e8-90de-e6c877e360be/43.jpg?w=750&auto=format",
      "/photos/toyotaFortuner/fortunerMain.jpeg",
    ],
    about:
      "The Diesel engine is 2755 cc while the Petrol engine is 2694 cc . It is available with Manual & Automatic transmission. Depending upon the variant and fuel type the Fortuner has a mileage of 10 kmpl . The Fortuner is a 7 seater 4 cylinder car and has length of 4795mm, width of 1855mm and a wheelbase of 2745mm.",
  },
  {
    id: 17,
    name: "Audi A4 sunroof",
    modal: "2014",
    price: "₹8-10K/day",
    type: "Automatic",
    mileage: "17km/L",
    engine: "1998 cc",
    fuelType: "diesel",
    imageUrls: [
      "/photos/audia4/2.jpg",
      "/photos/audia4/1.jpg",
      "/photos/audia4/audiMain.jpeg",
    ],
    about:
      "The Audi A4 has 1 Petrol Engine on offer. The Petrol engine is 1984 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the A4 has a mileage of . The A4 is a 5 seater 4 cylinder car and has length of 4762mm, width of 1847mm and a wheelbase of 2819mm.",
  },
  {
    id: 18,
    name: "KIA Seltos",
    modal: "2021",
    price: "₹2.5-3K/day",
    type: "Manual",
    mileage: "17km/L",
    engine: "1482 to 1497 cc",
    fuelType: "petrol",
    imageUrls: [
      "https://teamcardelight.com/wp-content/uploads/2022/01/kia-seltos-drive-review.jpeg",
      "/photos/kiaSaltos/1.jpg",
      "/photos/kiaSaltos/2.jpg",
      "/photos/kiaSaltos/kiaMain.jpg",
    ],
    about:
      "Kia Seltos is currently available in Petrol and Diesel engines. The 1482 cc Petrol engine generates a power of 157.81bhp@5500rpm and a torque of 253Nm@1500-3500rpm. The 1493 cc Diesel engine generates a power of 113.42bhp@6300rpm and a torque of 144Nm@4500rpm.",
  },
  {
    id: 19,
    name: "Maruti Swift",
    modal: "2016",
    price: "₹1.5-2K/day",
    type: "Manual",
    mileage: "20.4km/L",
    engine: "1197 cc",
    fuelType: "Desiel",
    imageUrls: [
      "/photos/swift/main.webp",
      "/photos/swift/1.jpg",
      "/photos/swift/2.jpg",
    ],
    about:
      "Maruti Swift 2016 is one of the best selling hatchbacks for the company. One of the most popular hatchbacks considered while buying a mid-size one. The second generation has been highly successful carrying forward first-generation's legacy",
  },
  {
    id: 20,
    name: "Maruti Alto K10",
    modal: "2018",
    price: "₹1.2-1.5K/day/hr",
    type: "Manual",
    mileage: "24 to 33km/L",
    engine: "	998 cc",
    fuelType: "Petrol",
    imageUrls: [
      "/photos/alto/1.avif",
      "/photos/alto/2.webp",
      "/photos/alto/3.jpg",
    ],
    about:
      "An affordable option for an entry-level car buyer, the new Alto K10, has improved on space, fit and finish, equipment, fuel efficiency, and performance. This new model still retains its positive traits of peppy performance, and driveability, along with Maruti's strong after-sales service network. But, crashworthiness and design are areas where the Alto doesn't score well.",
  },
  {
    id: 21,
    name: "Honda city",
    modal: "2011",
    price: "₹2-2.5K/day",
    type: "Automatic",
    mileage: "17 to 18km/L",
    engine: "1498 cc",
    fuelType: "Petrol",
    imageUrls: [
      "/photos/hondacity/main.avif",
      "/photos/hondacity/1.jpg",
      "/photos/hondacity/2.jpg",
    ],
    about:
      "Honda City comes with six airbags, ABS with EBD and traction control, a lane watch camera, a hill start assist, a powered window with anti-pinch, all seats with three-point seatbelts and headrests, ISOFIX anchor points, and TPMS. \nThe City has also scored five stars in the ASEAN NCAP tests.",
  },
  {
    id: 22,
    name: "Hyundai i20",
    modal: "2022",
    price: "₹2-2.5K/day",
    type: "Manual",
    mileage: "17 to 20km/L",
    engine: "1197 cc",
    fuelType: "Petrol",
    imageUrls: [
      "/photos/i20/main.jpg",
      "/photos/i20/1.avif",
      "/photos/i20/2.webp",
    ],
    about:
      "The new Hyundai i20 captures attention wherever it goes. A mesmerising new grille, resplendent DRLs and tail lamps make it a sight to behold. Its magnetic personality is sure to attract minds and hearts alike.",
  },
];

export const slides = [
  {
    quote: "Zero Worries",
    line: "Your journey, your pace!",
    url: "/carousel/1.webp",
  },
  {
    quote: "Effortless Elegance",
    line: "Elevate your travel experience with style and sophistication.",
    url: "/carousel/2.webp",
  },
  {
    quote: "Instant Adventure",
    line: "we make it easy to turn your travel plans into instant adventures.",
    url: "/carousel/3.webp",  
  },
  {
    quote: "Doorstep Delviery",
    line: "Don't worry about picking and droping your vehicles.",
    url: "/carousel/4.jpg",  
  },
];
